### ISSUE TITLE
Apply callback transaction throws keyerrors when retrying

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework-extensions#177]
```
2 11:10:40 NY1SRV0003 ovs-workers[25275]: 2018-09-02 11:10:40 48400 -0400 - NY1SRV0003 - 25275/139730481256192 - celery/celery.worker.job - 23988 - ERROR - Task celery.backend_cleanup[c617e3c7-62f0-4afb-ba94-d9cdcf424e61] raised unexpected: KeyError('96f9a814-46b1-4eeb-8908-0c6b23b01f43',)
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]: Traceback (most recent call last):
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:     R = retval = fun(*args, **kwargs)
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:     return self.run(*args, **kwargs)
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:   File "/usr/lib/python2.7/dist-packages/celery/app/builtins.py", line 36, in backend_cleanup
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:     app.backend.cleanup()
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:   File "/opt/OpenvStorage/ovs/extensions/celery/arakoonresult.py", line 182, in cleanup
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:     self._client.apply_callback_transaction(build_cleanup, max_retries=20)
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/storage/persistent/pyrakoonstore.py", line 44, in new_function
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:     return f(self, *args, **kw)
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/storage/persistent/pyrakoonstore.py", line 204, in apply_callback_transaction
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:     return self._client.apply_callback_transaction(transaction_callback, max_retries, retry_wait_function)
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 49, in new_function
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:     return f(self, *args, **kw)
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 474, in apply_callback_transaction
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:     return apply_callback_transaction(self)
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 86, in wrapped
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:     result = f(self, *args, **kwargs)
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 462, in apply_callback_transaction
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:     self.apply_transaction(transaction)
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 49, in new_function
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:     return f(self, *args, **kw)
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 86, in wrapped
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:     result = f(self, *args, **kwargs)
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 384, in apply_transaction
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]:     return self._client.sequence(self._sequences[transaction])
Sep  2 11:10:40 NY1SRV0003 ovs-workers[25275]: KeyError: '96f9a814-46b1-4eeb-8908-0c6b23b01f43'
```

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/framework-extensions/pull/181
Released in https://github.com/openvstorage/framework-extensions/releases/tag/0.1.7
